// Seed data for DriveMarket initial database setup
module.exports = {
  cars: [
    {
      id: 1,
      make: "Tesla",
      model: "Model 3",
      trim: "Long Range AWD",
      year: 2022,
      price: 31450.0,
      mileage: 28450,
      transmission: "Single-Speed Automatic",
      fuel_type: "Electric",
      body_style: "Sedan",
      drivetrain: "Dual Motor AWD",
      location: "Austin, TX",
      distance: "5 miles away",
      description: "Exceptional 2022 Tesla Model 3 Long Range Dual Motor AWD in Pearl White Multi-Coat. Full Self-Driving Computer 3.0 capability, Premium Black Interior, 19\" Sport Wheels, and pristine battery health at 96%. One meticulous owner, garage kept, no smoker, clean Texas title in hand. Includes Gen 2 Mobile Connector with NEMA 14-50 adapter.",
      seller_name: "Marcus Chen",
      seller_phone: "+1 (512) 555-0192",
      seller_rating: 4.9,
      seller_reviews: 42,
      seller_response: "Replies < 15 mins",
      deal_rating: "Great Deal",
      carfax_clean: 1,
      condition: "Excellent",
      highlights: "Full Self-Driving Capable, Dual Motor All-Wheel Drive, Premium Audio (14 Speakers), Heated Front & Rear Seats, All-Glass Panoramic Sunroof, 353 mi EPA Range, Clean Texas Title",
      photo_1: "sample_tesla_1",
      photo_2: "sample_tesla_2",
      photo_3: "sample_tesla_3",
      is_favorite: 0,
      is_user_listing: 0,
      created_at: Date.now() - (1000 * 60 * 60 * 3)
    },
    {
      id: 2,
      make: "Toyota",
      model: "RAV4",
      trim: "Hybrid XSE AWD",
      year: 2023,
      price: 34900.0,
      mileage: 19200,
      transmission: "eCVT Automatic",
      fuel_type: "Hybrid",
      body_style: "SUV",
      drivetrain: "Electronic On-Demand AWD",
      location: "Round Rock, TX",
      distance: "12 miles away",
      description: "2023 Toyota RAV4 Hybrid XSE in Blueprint with Two-Tone Midnight Black Metallic Roof. 40 MPG combined, sport-tuned suspension, 10.5\" multimedia screen with wireless Apple CarPlay/Android Auto. All maintenance done at Round Rock Toyota dealership.",
      seller_name: "Sarah Jenkins",
      seller_phone: "+1 (512) 555-0248",
      seller_rating: 5.0,
      seller_reviews: 19,
      seller_response: "Replies < 10 mins",
      deal_rating: "Great Deal",
      carfax_clean: 1,
      condition: "Excellent",
      highlights: "40 MPG Combined Efficiency, Electronic On-Demand AWD, Toyota Safety Sense 2.5+, SofTex-Trimmed Sport Seats, Two-Tone Black Roof, JBL 11-Speaker Audio",
      photo_1: "sample_rav4_1",
      photo_2: "sample_rav4_2",
      photo_3: "sample_rav4_3",
      is_favorite: 0,
      is_user_listing: 0,
      created_at: Date.now() - (1000 * 60 * 60 * 6)
    },
    {
      id: 3,
      make: "BMW",
      model: "330i",
      trim: "M Sport Package",
      year: 2021,
      price: 29800.0,
      mileage: 34100,
      transmission: "8-Speed Sport Automatic",
      fuel_type: "Gasoline",
      body_style: "Sedan",
      drivetrain: "Rear-Wheel Drive (RWD)",
      location: "Austin, TX",
      distance: "8 miles away",
      description: "2021 BMW 330i Sedan equipped with full factory M Sport package in Portimao Blue Metallic with Cognac Vernasca Leather. Includes shadowline trim, variable sport steering, Live Cockpit Pro with navigation, and active blind spot detection.",
      seller_name: "David Miller",
      seller_phone: "+1 (512) 555-0371",
      seller_rating: 4.8,
      seller_reviews: 28,
      seller_response: "Replies < 30 mins",
      deal_rating: "Fair Price",
      carfax_clean: 1,
      condition: "Good",
      highlights: "M Sport Aerodynamics Package, 19\" M Double-Spoke Bicolor Wheels, Cognac Vernasca Leather, Apple CarPlay & Android Auto, Active Driving Assistant, Sunroof",
      photo_1: "sample_bmw_1",
      photo_2: "sample_bmw_2",
      photo_3: "sample_bmw_3",
      is_favorite: 0,
      is_user_listing: 0,
      created_at: Date.now() - (1000 * 60 * 60 * 12)
    },
    {
      id: 4,
      make: "Honda",
      model: "Accord",
      trim: "Sport 2.0T",
      year: 2022,
      price: 26500.0,
      mileage: 26800,
      transmission: "10-Speed Automatic",
      fuel_type: "Gasoline",
      body_style: "Sedan",
      drivetrain: "Front-Wheel Drive (FWD)",
      location: "Cedar Park, TX",
      distance: "16 miles away",
      description: "2022 Honda Accord Sport 2.0T in Sonic Gray Pearl. Features the Civic Type-R derived 252hp 2.0-liter turbocharged engine paired with Honda's responsive 10-speed automatic with paddle shifters. Clean CARFAX 1-owner car.",
      seller_name: "Elena Rostova",
      seller_phone: "+1 (512) 555-0419",
      seller_rating: 4.9,
      seller_reviews: 14,
      seller_response: "Replies < 5 mins",
      deal_rating: "Great Deal",
      carfax_clean: 1,
      condition: "Excellent",
      highlights: "252-HP 2.0L Turbocharged VTEC, 10-Speed Automatic with Paddle Shifters, Wireless Apple CarPlay/Android Auto, Honda Sensing Suite, Blind Spot Information System",
      photo_1: "sample_accord_1",
      photo_2: "sample_accord_2",
      photo_3: "sample_accord_3",
      is_favorite: 0,
      is_user_listing: 0,
      created_at: Date.now() - (1000 * 60 * 60 * 24)
    },
    {
      id: 5,
      make: "Porsche",
      model: "911 Carrera",
      trim: "Coupe (992)",
      year: 2021,
      price: 98500.0,
      mileage: 14200,
      transmission: "8-Speed Porsche Doppelkupplung (PDK)",
      fuel_type: "Gasoline",
      body_style: "Coupe",
      drivetrain: "Rear-Wheel Drive (RWD)",
      location: "Austin, TX",
      distance: "4 miles away",
      description: "Striking 2021 Porsche 911 Carrera (992 generation) finished in GT Silver Metallic over Bordeaux Red leather interior. Twin-turbo 3.0L Boxer 6 generating 379 hp. Equipped with Sport Chrono Package, Sport Exhaust System, and 20\"/21\" Carrera Classic Wheels.",
      seller_name: "Austin Prestige Motors",
      seller_phone: "+1 (512) 555-0899",
      seller_rating: 5.0,
      seller_reviews: 87,
      seller_response: "Replies < 5 mins",
      deal_rating: "Fair Price",
      carfax_clean: 1,
      condition: "Excellent",
      highlights: "Sport Chrono Package with Mode Switch, Factory Sport Exhaust System with Black Tailpipes, 20\"/21\" Carrera Classic Wheels, Bose Surround Sound, Bordeaux Red Leather",
      photo_1: "sample_porsche_1",
      photo_2: "sample_porsche_2",
      photo_3: "sample_porsche_3",
      is_favorite: 0,
      is_user_listing: 0,
      created_at: Date.now() - (1000 * 60 * 60 * 36)
    },
    {
      id: 6,
      make: "Ford",
      model: "Bronco",
      trim: "Badlands 4x4",
      year: 2023,
      price: 46200.0,
      mileage: 15400,
      transmission: "10-Speed Automatic",
      fuel_type: "Gasoline",
      body_style: "Truck",
      drivetrain: "Advanced 4x4 with Automatic On-Demand",
      location: "San Marcos, TX",
      distance: "28 miles away",
      description: "2023 Ford Bronco Badlands 4-Door in Area 51 Blue. Equipped with the Sasquatch Package, 35\" Goodyear Territory tires, front and rear locking differentials, Bilstein position-sensitive dampers, and modular steel bumper.",
      seller_name: "Travis County Off-Road",
      seller_phone: "+1 (512) 555-0633",
      seller_rating: 4.7,
      seller_reviews: 31,
      seller_response: "Replies < 20 mins",
      deal_rating: "Great Deal",
      carfax_clean: 1,
      condition: "Excellent",
      highlights: "Sasquatch Package with 35\" Tires, Electronic-Locking Front & Rear Axles, Bilstein Position-Sensitive Monotube Shocks, Removable Hardtop & Doors, Trail Turn Assist",
      photo_1: "sample_bronco_1",
      photo_2: "sample_bronco_2",
      photo_3: "sample_bronco_3",
      is_favorite: 0,
      is_user_listing: 0,
      created_at: Date.now() - (1000 * 60 * 60 * 48)
    }
  ],
  messages: [
    {
      car_id: 1,
      sender_name: "Alex",
      message_text: "Hi Marcus, is the car still available? Clean title in hand?",
      timestamp: Date.now() - (1000 * 60 * 25),
      is_from_user: 1,
      is_system: 0,
      is_official_offer: 0,
      offer_amount: 0.0,
      original_price: 0.0
    },
    {
      car_id: 1,
      sender_name: "Marcus Chen",
      message_text: "Hi Alex! Yes, title is clean and ready. Battery health is tested at 96%.",
      timestamp: Date.now() - (1000 * 60 * 22),
      is_from_user: 0,
      is_system: 0,
      is_official_offer: 0,
      offer_amount: 0.0,
      original_price: 0.0
    },
    {
      car_id: 1,
      sender_name: "System",
      message_text: "Alex made an offer of $29,800",
      timestamp: Date.now() - (1000 * 60 * 18),
      is_from_user: 0,
      is_system: 1,
      is_official_offer: 0,
      offer_amount: 0.0,
      original_price: 0.0
    },
    {
      car_id: 1,
      sender_name: "Official Offer",
      message_text: "Official Offer Received",
      timestamp: Date.now() - (1000 * 60 * 15),
      is_from_user: 0,
      is_system: 0,
      is_official_offer: 1,
      offer_amount: 29800.0,
      original_price: 31450.0
    }
  ]
};
